AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'omnievent.gemspec'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
